### PR TITLE
multiple-tables

### PR DESCRIPTION
**Pull request by Patfarmurs**
Screenshot1-day3
Screenshot2-day3

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi, @Patfarmurs, 

terminator

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have professional documentation, please edit your README file according to the current project and be organized in your PR if you have 7 queries there should be 7 screenshots.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Patfarmurs** [comment]
Hi @franclobo thanks for your review, you can see that all 7 tables and the queries are there. Your comment is vague. What else do you want me to add to my README file?

**Review by didierganthier — APPROVED** [review]
Hi @Patfarmurs ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀



## Highlights
- Added changes to the table structure in the `schema.sql` file. ✔️ 
- Added everything that populates tables with data in the `data.sql` file. ✔️ 
- Added everything that is a query that helps to analyze data in the `queries.sql` file. ✔️ 

## Optional Suggestions 💡
- N/A

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

**Comment by Patfarmurs** [comment]
Thank you @didierganthier

**Pull request merged**
